<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>

    <title><?= $this->translate("Welcome to UMI.Framework") ?> | <?= $this->translate("Home") ?></title>

    <?php
    echo $this->headStyle()
        ->prependFile('/css/foundation.min.css')
        ->prependFile('/css/normalize.min.css');
    ?>

    <script src="/js/vendor/custom.modernizr.js"></script>
</head>
<body>
<div class="row">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-12 columns">

                <nav class="top-bar">
                    <ul class="title-area">
                        <li class="name">
                            <h1><a href="<?= $this->url('home', [], true) ?>">UMI.Framework</a></h1>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="row" style="margin-top: 25px"><?php
            echo $content;
            ?></div>

        <footer class="row">
            <div class="large-12 columns">
                <hr/>
                <div class="row">
                    <div class="small-offset-6 small-6 columns text-right">
                        <small><?= $this->translate("&copy; Umisoft ltd. 2007-2013") ?></small>
                    </div>
                </div>
            </div>
        </footer>

    </div>
</div>
<?php
echo $this->headScript()
    ->prependScript(
        '$(document).foundation();'
    )
    ->prependFile('/js/foundation.min.js')
    ->prependFile('/js/vendor/jquery.js');
?>
</body>
</html>